# See https://domluna.github.io/JuliaFormatter.jl/stable/ for a list of options
whitespace_ops_in_indices = true
remove_extra_newlines = true
always_for_in = true
whitespace_typedefs = true
normalize_line_endings = "unix"
# format_docstrings = true
# format_markdown = true
